import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Đánh giá mức độ trưởng thành về quản trị trải nghiệm khách hàng",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Quản trị trải nghiệm khách hàng - Lắng nghe và phản hồi</title>
        <meta
          name="description"
          content="Khám phá cách quản trị trải nghiệm khách hàng hiệu quả, từ lắng nghe phản hồi đến cải thiện sản phẩm dịch vụ."
        />
        <meta
          name="keywords"
          content="Quản trị trải nghiệm khách hàng, Lắng nghe khách hàng, Phản hồi khách hàng, Cải thiện dịch vụ"
        />
        <meta name="robots" content="index, follow" />

        <meta
          property="og:title"
          content="Quản trị trải nghiệm khách hàng - Lắng nghe & phản hồi"
        />
        <meta
          property="og:description"
          content="Cách quản trị trải nghiệm khách hàng hiệu quả, tối ưu phản hồi để nâng cao dịch vụ."
        />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://yourwebsite.com" />
        <meta
          property="og:image"
          content="https://yourwebsite.com/images/customer-experience.jpg"
        />

        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Quản trị trải nghiệm khách hàng" />
        <meta
          name="twitter:description"
          content="Lắng nghe khách hàng & tối ưu dịch vụ của bạn."
        />
        <meta
          name="twitter:image"
          content="https://yourwebsite.com/images/customer-experience.jpg"
        />

        <link rel="canonical" href="https://yourwebsite.com" />
      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
